### ISSUE TITLE
Melhorar visibilidade do Readme.md 

### ISSUE THREAD

**Issue by noejunior299** [nferdica/nferdica#1]
Gostaria que a imagem que mostra a contribuição no github estivesse com fundo escuro, isso iria conjugar com o Readme.md além de que ajuda para as pessoas com problemas na visão(como eu kk).

![Captura de ecrã 2024-08-07 165243](https://github.com/user-attachments/assets/65f9eb5b-c7c2-49d7-8472-d1a3db962fb1)

**Comment by nferdica** [comment]
Problema resolvido meu amigo, obrigado pela dica! 

![image](https://github.com/user-attachments/assets/8dbb60e1-404a-49e8-989e-6dd73ff8ed88)

**Comment by noejunior299** [comment]
De nada, melhorou bastante 🔥!.
